### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by egeorjon** [egeorjon/GoLyat#16]
References:
* [(Netlify) Hugo tips: How to create author pages](https://www.netlify.com/blog/2018/07/24/hugo-tips-how-to-create-author-pages/)
* Universe theme

**Comment by egeorjon** [comment]
```toml
[params.Footer.Top]
  
  [[params.Footer.Top.Groups]]
    columns = { "sm" = 2, "md" = 2, "lg" = 2, "xl" = 2 }

    [[params.Footer.Top.Groups.Widgets]]
      wtype  = "logo"
      cache  = true
      params = { "image" = "/assets/img/site-logo.png", "title" = "Le blog d'Emmanuel GEORJON", "width" = 75 , "height" = 75 }
      weight = 1

    [[params.Footer.Top.Groups.Widgets]]
      wtype  = "follow-me"
      cache  = true
      params = { }
      weight = 2

[params.Footer.Main]
  columns = { "sm" = 1, "md" = 2, "lg" = 2, "xl" = 2 }

  [[params.Footer.Main.Groups]]
    columns = { "sm" = 1, "md" = 1, "lg" = 1, "xl" = 1 }

    [[params.Footer.Main.Groups.Widgets]]
      wtype  = "page"
      cache  = true
      params = { "page" = "a-propos" }
      weight = 1

  [[params.Footer.Main.Groups]]
    columns = { "sm" = 1, "md" = 1, "lg" = 1, "xl" = 1 }

    [[params.Footer.Main.Groups.Widgets]]
      wtype  = "page"
      cache  = true
      params = { "page" = "links" }
      weight = 1
    [[params.Footer.Main.Groups.Widgets]]
      wtype  = "most-popular"
      cache  = true
      params = { "filename" = "popularposts.json", "numposts" = 5 }
      weight = 2
# 
```

**Comment by egeorjon** [comment]
Readme with table of content
[goLyat.md](https://github.com/egeorjon/GoLyat/files/8521975/goLyat.md)

**Comment by egeorjon** [comment]
Reference: https://www.netlify.com/blog/2018/07/24/hugo-tips-how-to-create-author-pages/

**Comment by egeorjon** [comment]
```toml
[[params.Single.Rows]]
name = "authors"
columns = { "sm" = 1, "md" = 1, "lg" = 1, "xl" = 1 }

[[params.Single.Rows.Widgets]]
  wtype  = "authors"
  cache  = false
  params = { }
  weight = 1

[[params.Single.Rows]]
name = "tags-share"
columns = { "sm" = 1, "md" = 2, "lg" = 2, "xl" = 2 }

[[params.Single.Rows.Widgets]]
  wtype  = "post-tags"
  cache  = false
  params = { }
  weight = 1
[[params.Single.Rows.Widgets]]
  wtype  = "share-links"
  cache  = false
  params = { }
  weight = 2

[[params.Single.Rows]]
name         = "related"
limitedWidth = false
columns      = { "sm" = 1, "md" = 1, "lg" = 1, "xl" = 1 }

[[params.Single.Rows.Widgets]]
  wtype  = "related-posts"
  cache  = false
  params = { }
  weight = 1

```
